//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.VariableDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class VariableDataSource { }
#else

	public class VariableDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public VariableDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/Prototype.Screens;component/SampleData/VariableDataSource/VariableDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Variables _Variables = new Variables();

		public Variables Variables
		{
			get
			{
				return this._Variables;
			}
		}
	}

	public class VariablesItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private double _Address = 0;

		public double Address
		{
			get
			{
				return this._Address;
			}

			set
			{
				if (this._Address != value)
				{
					this._Address = value;
					this.OnPropertyChanged("Address");
				}
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private double _Value = 0;

		public double Value
		{
			get
			{
				return this._Value;
			}

			set
			{
				if (this._Value != value)
				{
					this._Value = value;
					this.OnPropertyChanged("Value");
				}
			}
		}

		private string _Unit = string.Empty;

		public string Unit
		{
			get
			{
				return this._Unit;
			}

			set
			{
				if (this._Unit != value)
				{
					this._Unit = value;
					this.OnPropertyChanged("Unit");
				}
			}
		}

		private string _Range = string.Empty;

		public string Range
		{
			get
			{
				return this._Range;
			}

			set
			{
				if (this._Range != value)
				{
					this._Range = value;
					this.OnPropertyChanged("Range");
				}
			}
		}
	}

	public class Variables : System.Collections.ObjectModel.ObservableCollection<VariablesItem>
	{ 
	}
#endif
}
